### PR TITLE
Fix: DO-2692 causal graph tooltip quirks with visibility

### PR DESCRIPTION
**Pull request by krzysztof-causalens**
## Motivation and Context

The original causal graph viewer tooltip implementation did not account for the viewer being out of view due to overflowing in e.g. a scrollable container or a collapse/accordion style component.
This resulted in the tooltips being displayed in seemingly random places, when hovering over where the graph would be if it wasn't for the fact that it's currently hidden. There were also other quirks where the tooltip wouldn't disappear correctly when moving the mouse out of the graph.

## Implementation Description

Implemented few fixes:
1. Tooltip is now explicitly set to null `onMouseLeave` of the graph pane - this fixes scenarios where a node is right on the border of the graph view, and previously moving the mouse out of the view kept the tooltip on. Also added a `contentvisibility` listener so focusing out of the window also hides the active tooltip.

https://github.com/causalens/dara-ui/assets/87647189/e000d373-78d7-410c-b0e4-a720477313c6

2. Added a continuous IntersectionObserver which observes whether the graph pane is currently visible (at all, meaning if at least a few pixels of it are in the viewport and visible); this is used when attempting to set tooltip content to short-circuit and prevent them from being displayed on e.g. graphs within a collapsed accordion.

https://github.com/causalens/dara-ui/assets/87647189/3753f9bd-2f58-46c8-88ea-f6e388a7eebd

(this used to show tooltips over the hidden graph)

3. When attempting to show a tooltip and the above check succeeded, we perform a one-time check spawning a new intersection observer to check whether the tooltip would appear over a visible part of the graph. This can't use the previous continuous IntersectionObserver as that one only fires events when the graph first moves in or out of view, and we need more accurate information on its position. I didn't find a better way than spawning a new observer.
If the logic detects a partially visible graph, we check the tooltip's position - whether it's over the visible part of the graph.

https://github.com/causalens/dara-ui/assets/87647189/7f930f2c-83cf-4fc4-93f6-a390106c60cf

Extracted the tooltip-related logic into separate hooks not to pollute the main graph file further.

## How Has This Been Tested?

Manually, added two stories to test a scrollable and a collapsible scenario

## PR Checklist:

- [x] I have implemented all requirements? (see JIRA, project documentation).
- [x] I am not affecting someone else's work, If I am, they are included as a reviewer.
- [x] I have added relevant tests (unit, integration or regression).
- [ ] I have added comments to all the bits that are hard to follow.
- [ ] I have added/updated Documentation.
- [ ] I have updated the appropriate changelog with a line for my changes.

### CODE REVIEW

**Comment by krzysztof-causalens** [comment]
I'd appreciate if someone could have a play around with the new stories locally (perhaps @patricia-causalens or @Roman-Kornev would have the repo checked out already). From my manual testing these fixes seem to cover issues I could find with the tooltip behaviour within scrollable or collapsible containers but it would be good to have another pair of eyes confirm that it all works as expected.

**Comment by patricia-causalens** [comment]
> I'd appreciate if someone could have a play around with the new stories locally (perhaps @patricia-causalens or @Roman-Kornev would have the repo checked out already). From my manual testing these fixes seem to cover issues I could find with the tooltip behaviour within scrollable or collapsible containers but it would be good to have another pair of eyes confirm that it all works as expected.

I tried as well and seems to be fixed to me :)

**Review by patricia-causalens — APPROVED** [review]
Missing changelog but otherwise LGTM, tried it as well locally. Nicely explained comments :)

**Review by tamara-causalens — APPROVED** [review]
Awesome stuff!

**Pull request merged**
